# Generated by Django 5.2.4 on 2025-09-07 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('', 'Select'), ('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Python', 'Python'), ('Full Stack', 'Full Stack'), ('DevOps', 'DevOps'), ('Networking', 'Networking'), ('Linux', 'Linux'), ('.NET', '.NET'), ('MEAN', 'MEAN'), ('MERN', 'MERN'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('Drupal', 'Drupal'), ('Finance', 'Finance'), ('HR', 'HR'), ('Digital Marketing', 'Digital Marketing'), ('Business Analyst', 'Business Analyst'), ('Sales Analyst', 'Sales Analyst'), ('Administration', 'Administration')], max_length=100)),
                ('assessor_name', models.CharField(max_length=100)),
                ('assessment_date', models.DateField()),
                ('topics', models.TextField()),
                ('assessment_number', models.IntegerField(choices=[(1, 'Assessment 1'), (2, 'Assessment 2'), (3, 'Assessment 3')])),
                ('total_marks', models.IntegerField(default=0, editable=False, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('qualification', models.CharField(choices=[('', 'Select Qualification'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=50)),
                ('college_name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('', 'Select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('area_of_interest', models.CharField(choices=[('', 'Select'), ('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Python', 'Python'), ('Full Stack', 'Full Stack'), ('DevOps', 'DevOps'), ('Networking', 'Networking'), ('Linux', 'Linux'), ('.NET', '.NET'), ('MEAN', 'MEAN'), ('MERN', 'MERN'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('Drupal', 'Drupal'), ('Finance', 'Finance'), ('HR', 'HR'), ('Digital Marketing', 'Digital Marketing'), ('Business Analyst', 'Business Analyst'), ('Sales Analyst', 'Sales Analyst'), ('Administration', 'Administration')], max_length=100)),
                ('preferred_start_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('project_duration', models.CharField(blank=True, max_length=50)),
                ('prior_internship', models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('past_internship_details', models.TextField(blank=True)),
                ('internship_type', models.CharField(choices=[('', 'Select'), ('Offline', 'Offline'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=10)),
                ('skills', models.TextField(blank=True)),
                ('bonafide', models.FileField(upload_to='bonafide/')),
                ('linkedin', models.URLField()),
                ('heard_from', models.CharField(blank=True, choices=[('', 'Select'), ('BG Employee', 'BG Employee'), ('From Google Reviews', 'From Google Reviews'), ('Friends', 'Friends'), ('Through Social Media', 'Through Social Media'), ('Relation', 'Relation'), ('Existing Employees', 'Existing Employees')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skill', models.PositiveSmallIntegerField(default=0)),
                ('analytical_skills', models.PositiveSmallIntegerField(default=0)),
                ('troubleshooting', models.PositiveSmallIntegerField(default=0)),
                ('verbal_communication', models.PositiveSmallIntegerField(default=0)),
                ('written_communication', models.PositiveSmallIntegerField(default=0)),
                ('collaboration', models.PositiveSmallIntegerField(default=0)),
                ('time_management', models.PositiveSmallIntegerField(default=0)),
                ('work_ethic', models.PositiveSmallIntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0, editable=False)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_of_improvement', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='register.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='trainee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='register.intern'),
        ),
    ]
