# Generated by Django 5.2.4 on 2025-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
